services:
  app:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev

  node:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  redis:
    image: redis:7
    ports:
      - "6379:6379"
